# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishWord', models.CharField(max_length=100)),
                ('maoriWord', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
