# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordrecord',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
