# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordproject', '0003_auto_20160331_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordrecord',
            old_name='dateCreate',
            new_name='dateCreated',
        ),
    ]
